# Generated by Django 4.2.9 on 2024-02-04 15:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_alter_petowner_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.URLField(blank=True, db_index=True, max_length=128, unique=True, verbose_name='Trip Number'),
        ),
    ]
